############# English navigation ##############

# main menu
[[main]]
name = "Inicio"
pageRef = "/"
weight = 1

[[main]]
name = "Sobre Nosotros"
pageRef = "authors"
weight = 2

[[main]]
name = "Colabora"
pageRef = "collaborate"
weight = 3


# footer menu
[[footer]]
name = "Sobre Nosotros"
pageRef = "sobre-nosotros"
weight = 1

[[footer]]
name = "Pólitica Privacidad"
pageRef = "politica-privacidad"
weight = 3
