# main menu
[[main]]
name = "Home"
pageRef = "/"
weight = 1

[[main]]
name = "About Us"
pageRef = "authors"
weight = 2

[[main]]
name = "Collaborate"
pageRef = "collaborate"
weight = 3

# footer menu
[[footer]]
name = "About Us"
pageRef = "authors"
weight = 1

[[footer]]
name = "Privacy Policy"
pageRef = "privacy-policy"
weight = 3