# main menu
[[main]]
name = "Home"
pageRef = "/"
weight = 1

[[main]]
name = "About Us"
pageRef = "about-us"
weight = 2

#[[main]]
#name = "Blog"
#pageRef = "blog"
#weight = 3

# footer menu
[[footer]]
name = "About Us"
pageRef = "about-us"
weight = 1

[[footer]]
name = "Privacy Policy"
pageRef = "privacy-policy"
weight = 3