# menú principal
[[main]]
name = "Inici"
pageRef = "/"
weight = 1

[[main]]
name = "Sobre Nosaltres"
pageRef = "authors"
weight = 2

[[main]]
name = "Col·labora"
pageRef = "collaborates"
weight = 3

# menú del peu de pàgina
[[footer]]
name = "Sobre Nosaltres"
pageRef = "authors"
weight = 1

[[footer]]
name = "Política de Privacitat"
pageRef = "politica-de-privacitat"
weight = 3