# menú principal
[[main]]
name = "Inici"
pageRef = "/"
weight = 1

[[main]]
name = "Sobre Nosaltres"
pageRef = "sobre-nosaltres"
weight = 2

[[main]]
name = "Blog"
pageRef = "blog"
weight = 3

# menú del peu de pàgina
[[footer]]
name = "Sobre Nosaltres"
pageRef = "sobre-nosaltres"
weight = 1

[[footer]]
name = "Política de Privacitat"
pageRef = "politica-de-privacitat"
weight = 3